/**
 * Your recommendation data goes here!
 *
 * Replace this example with your own domain (movies, restaurants, games, etc.)
 * Keep the same structure: an object with an "options" array.
 *
 * Each option should have properties that help you make recommendations.
 * Think about: What information do I need to match user preferences?
 */

const data = {
  // Describe your domain
  domain: "Pets",
  description: "What pet should I get? This recommendation tool helps you decide which type of pet is best for you!",

  // Your options array - aim for 15-25 items
  options: [
      {
      name: "Cat",
      species: "Mammal",
      temperament: "relaxed",
      size: "small",
      lifeSpan: 15,
      adoptionFeeAvg: 100,
      maintenanceLevel: "low",
      },
      {
      name: "Goldfish",
      species: "Fish",
      temperament: "calm",
      size: "tiny",
      lifeSpan: 10,
      adoptionFeeAvg: 20,
      maintenanceLevel: "low",
      },
      {
        name: "Dog",
        species: "Mammal",
        temperament: "friendly",
        size: "medium",
        lifeSpan: 13,
        adoptionFeeAvg: 150,
        maintenanceLevel: "medium",
      },
      {
        name: "Parakeet",
        species: "Bird",
        temperament: "social",
        size: "tiny",
        lifeSpan: 8,
        adoptionFeeAvg: 30,
        maintenanceLevel: "medium",
      },
      {
        name: "Rabbit",
        species: "Mammal",
        temperament: "gentle",
        size: "small",
        lifeSpan: 9,
        adoptionFeeAvg: 50,
        maintenanceLevel: "medium",
      },
      {
        name: "Hamster",
        species: "Mammal",
        temperament: "playful",
        size: "tiny",
        lifeSpan: 3,
        adoptionFeeAvg: 15,
        maintenanceLevel: "low",
      },
      {
        name: "Corn Snake",
        species: "Reptile",
        temperament: "docile",
        size: "medium",
        lifeSpan: 15,
        adoptionFeeAvg: 80,
        maintenanceLevel: "medium",
      },
      {
        name: "Leopard Gecko",
        species: "Reptile",
        temperament: "calm",
        size: "small",
        lifeSpan: 20,
        adoptionFeeAvg: 60,
        maintenanceLevel: "low",
      },
      {
        name: "African Grey Parrot",
        species: "Bird",
        temperament: "intelligent",
        size: "medium",
        lifeSpan: 50,
        adoptionFeeAvg: 1200,
        maintenanceLevel: "high",
      },
      {
        name: "Guinea Pig",
        species: "Mammal",
        temperament: "gentle",
        size: "small",
        lifeSpan: 6,
        adoptionFeeAvg: 25,
        maintenanceLevel: "medium",
      },
      {
        name: "Tarantula",
        species: "Invertebrate",
        temperament: "quiet",
        size: "small",
        lifeSpan: 10,
        adoptionFeeAvg: 40,
        maintenanceLevel: "low",
      },
      {
        name: "Ferret",
        species: "Mammal",
        temperament: "curious",
        size: "small",
        lifeSpan: 7,
        adoptionFeeAvg: 100,
        maintenanceLevel: "high",
      },
      {
        name: "Bearded Dragon",
        species: "Reptile",
        temperament: "friendly",
        size: "medium",
        lifeSpan: 12,
        adoptionFeeAvg: 70,
        maintenanceLevel: "medium",
      },
      {
        name: "Axolotl",
        species: "Amphibian",
        temperament: "calm",
        size: "small",
        lifeSpan: 15,
        adoptionFeeAvg: 50,
        maintenanceLevel: "medium",
      },
      {
        name: "Budgerigar",
        species: "Bird",
        temperament: "cheerful",
        size: "tiny",
        lifeSpan: 7,
        adoptionFeeAvg: 25,
        maintenanceLevel: "medium",
      },
      {
        name: "Hermit Crab",
        species: "Invertebrate",
        temperament: "quiet",
        size: "tiny",
        lifeSpan: 10,
        adoptionFeeAvg: 10,
        maintenanceLevel: "low",
      },
      {
        name: "Chinchilla",
        species: "Mammal",
        temperament: "shy",
        size: "small",
        lifeSpan: 12,
        adoptionFeeAvg: 150,
        maintenanceLevel: "medium",
      },
      {
        name: "Red-Eared Slider",
        species: "Reptile",
        temperament: "calm",
        size: "medium",
        lifeSpan: 30,
        adoptionFeeAvg: 40,
        maintenanceLevel: "medium",
      },
      {
        name: "Frog",
        species: "Amphibian",
        temperament: "quiet",
        size: "small",
        lifeSpan: 8,
        adoptionFeeAvg: 15,
        maintenanceLevel: "low",
      },
      {
        name: "Horse",
        species: "Mammal",
        temperament: "intelligent",
        size: "large",
        lifeSpan: 25,
        adoptionFeeAvg: 2000,
        maintenanceLevel: "very high",
      },
      {
        name: "Rat",
        species: "Mammal",
        temperament: "smart",
        size: "small",
        lifeSpan: 3,
        adoptionFeeAvg: 20,
        maintenanceLevel: "medium",
      },
      {
        name: "Canary",
        species: "Bird",
        temperament: "cheerful",
        size: "tiny",
        lifeSpan: 10,
        adoptionFeeAvg: 35,
        maintenanceLevel: "medium",
      },
      {
        name: "Turtle",
        species: "Reptile",
        temperament: "calm",
        size: "small",
        lifeSpan: 40,
        adoptionFeeAvg: 50,
        maintenanceLevel: "medium",
      },
      {
        name: "Betta Fish",
        species: "Fish",
        temperament: "solitary",
        size: "tiny",
        lifeSpan: 5,
        adoptionFeeAvg: 10,
        maintenanceLevel: "low",
      },
      {
        name: "Iguana",
        species: "Reptile",
        temperament: "independent",
        size: "large",
        lifeSpan: 20,
        adoptionFeeAvg: 100,
        maintenanceLevel: "high",
      },
  ],
};

// Note: This file is loaded via a script tag, so `data` becomes a global variable
// that matching.js and app.js can access.
